# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    name: Deploy app to VPS
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install openssh
        run: sudo apt-get install openssh-client
      
      - name: Create ssh key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: echo "$SSH_KEY" > ./id_rsa
        
      - name: Copy code using scp
        env:
          SSH_IP: ${{ secrets.SSH_IP }}
        run: scp -i ./id_rsa . "cyber2k20@$SSH_IP:/var/www/cyber2k20"
